"use client";

import { ChangeEvent, DragEvent, useMemo, useRef, useState } from "react";

type Provider = "openai" | "gemini";
type Step = 1 | 2 | 3;
type Status = "idle" | "reading" | "generating" | "success" | "error";

const MAX_FILE_SIZE = 10 * 1024 * 1024;
const MAX_TEXT_LENGTH = 200_000;
const MODELS: Record<Provider, { label: string; id: string }> = {
  openai: { label: "Luna", id: "gpt-5.6-luna" },
  gemini: { label: "Gemini 3.5 Flash-Lite", id: "gemini-3.5-flash-lite" },
};
const STYLES = [
  { value: "formal", label: "공식 회의록", note: "보고서에 바로 붙여 넣는 정중한 문체" },
  { value: "concise", label: "간결 요약", note: "핵심 논점과 결정만 빠르게 확인" },
  { value: "decision", label: "결정 중심", note: "결정사항과 후속 조치를 가장 선명하게" },
];
const LENGTHS = [
  { value: "short", label: "짧게", note: "핵심만" },
  { value: "standard", label: "표준", note: "균형 있게" },
  { value: "detailed", label: "상세하게", note: "논의 근거까지" },
];

function renderMarkdown(markdown: string) {
  return markdown.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^### (.*)$/gm, "<h3>$1</h3>").replace(/^## (.*)$/gm, "<h2>$1</h2>").replace(/^# (.*)$/gm, "<h1>$1</h1>")
    .replace(/^\|(.+)\|$/gm, (line) => { const cells = line.split("|").slice(1, -1).map((cell) => cell.trim()); if (cells.every((cell) => /^[-: ]+$/.test(cell))) return ""; return `<div class="md-table-row">${cells.map((cell) => `<span>${cell}</span>`).join("")}</div>`; })
    .replace(/^- (.*)$/gm, "<li>$1</li>").replace(/^(\d+)\. (.*)$/gm, "<li>$2</li>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\n{2,}/g, "<br /><br />").replace(/\n/g, "<br />");
}

async function extractDocxText(file: File) {
  const bytes = new Uint8Array(await file.arrayBuffer()); const view = new DataView(bytes.buffer); const decoder = new TextDecoder("utf-8"); let end = -1;
  for (let i = bytes.length - 22; i >= Math.max(0, bytes.length - 65_557); i -= 1) if (view.getUint32(i, true) === 0x06054b50) { end = i; break; }
  if (end < 0) throw new Error("DOCX 압축 구조를 읽을 수 없습니다.");
  const centralSize = view.getUint32(end + 12, true); const centralOffset = view.getUint32(end + 16, true); let cursor = centralOffset; let documentXml: string | null = null;
  while (cursor < centralOffset + centralSize) {
    if (view.getUint32(cursor, true) !== 0x02014b50) break;
    const method = view.getUint16(cursor + 10, true); const compressedSize = view.getUint32(cursor + 20, true); const fileNameLength = view.getUint16(cursor + 28, true); const extraLength = view.getUint16(cursor + 30, true); const commentLength = view.getUint16(cursor + 32, true); const localOffset = view.getUint32(cursor + 42, true); const name = decoder.decode(bytes.slice(cursor + 46, cursor + 46 + fileNameLength));
    if (name === "word/document.xml") { const localNameLength = view.getUint16(localOffset + 26, true); const localExtraLength = view.getUint16(localOffset + 28, true); const start = localOffset + 30 + localNameLength + localExtraLength; const compressed = bytes.slice(start, start + compressedSize); const raw = method === 0 ? compressed : await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream("deflate-raw"))).arrayBuffer(); documentXml = decoder.decode(raw); }
    cursor += 46 + fileNameLength + extraLength + commentLength;
  }
  if (!documentXml) throw new Error("DOCX 본문을 찾을 수 없습니다."); const xml = new DOMParser().parseFromString(documentXml, "application/xml"); if (xml.querySelector("parsererror")) throw new Error("DOCX 본문을 해석할 수 없습니다."); const ns = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"; const body = xml.getElementsByTagNameNS(ns, "body")[0]; const output: string[] = [];
  Array.from(body?.children ?? []).forEach((element) => { if (element.localName === "p") { const text = Array.from(element.getElementsByTagNameNS(ns, "t")).map((node) => node.textContent ?? "").join("").trim(); if (text) output.push(text); } if (element.localName === "tbl") Array.from(element.getElementsByTagNameNS(ns, "tr")).forEach((row) => { const cells = Array.from(row.getElementsByTagNameNS(ns, "tc")).map((cell) => Array.from(cell.getElementsByTagNameNS(ns, "t")).map((node) => node.textContent ?? "").join("").trim()); if (cells.some(Boolean)) output.push(cells.join(" | ")); }); });
  return output.join("\n").slice(0, MAX_TEXT_LENGTH);
}

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null); const [step, setStep] = useState<Step>(1); const [provider, setProvider] = useState<Provider>("openai"); const [apiKey, setApiKey] = useState(""); const [file, setFile] = useState<File | null>(null); const [transcript, setTranscript] = useState(""); const [style, setStyle] = useState("formal"); const [length, setLength] = useState("standard"); const [result, setResult] = useState(""); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState(""); const model = useMemo(() => MODELS[provider], [provider]);
  async function acceptFile(nextFile?: File) { if (!nextFile) return; setError(""); setStatus("reading"); if (!nextFile.name.toLowerCase().endsWith(".docx")) { setError("DOCX 파일만 업로드할 수 있습니다."); setStatus("error"); return; } if (nextFile.size > MAX_FILE_SIZE) { setError("파일 크기는 10MB 이하만 지원합니다."); setStatus("error"); return; } try { const text = await extractDocxText(nextFile); if (!text.trim()) throw new Error("DOCX에서 읽을 수 있는 본문이 없습니다."); setFile(nextFile); setTranscript(text); setStatus("idle"); } catch (err) { setError(err instanceof Error ? err.message : "파일을 읽지 못했습니다."); setStatus("error"); } }
  function canContinue() { if (!apiKey.trim()) { setError("선택한 API의 키를 입력해 주세요."); return false; } if (!transcript.trim()) { setError("DOCX를 업로드하거나 회의록 전문을 직접 입력해 주세요."); return false; } setError(""); return true; }
  async function generateMinutes() { if (!canContinue()) { setStep(1); return; } setError(""); setStep(3); setStatus("generating"); try { const response = await fetch("/api/summarize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, model: model.id, apiKey, transcript, style, length }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "요약 요청에 실패했습니다."); setResult(data.markdown); setApiKey(""); setStatus("success"); } catch (err) { setError(err instanceof Error ? err.message : "요약 중 오류가 발생했습니다."); setStatus("error"); } }
  function downloadResult() { const blob = new Blob([result], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "회의록.md"; anchor.click(); URL.revokeObjectURL(url); }
  return <main><header className="topbar"><div className="brand"><span className="brand-mark">M</span><span>회의록 자동 생성기</span></div><span className="privacy-note">키와 문서는 저장하지 않습니다</span></header><section className="hero"><div className="eyebrow">MEETING MINUTES / IPO</div><h1>회의록을 만드는<br /><em>가장 짧은 흐름.</em></h1><p>입력하고, 다듬고, 가져가세요. 복잡한 전사문을 실무용 보고서로 바꾸는 3단계 워크스페이스입니다.</p></section><nav className="stepper" aria-label="회의록 생성 단계">{(["Input", "Process", "Output"] as const).map((label, index) => { const current = (index + 1) as Step; return <button key={label} className={step === current ? "current" : step > current ? "done" : ""} onClick={() => { if (current < step) setStep(current); }}><span>{String(current).padStart(2, "0")}</span>{label}</button>; })}</nav><section className="stage-shell">
    {step === 1 && <div className="stage-page"><div className="stage-title"><span className="stage-kicker">01 / INPUT</span><h2>회의록에 필요한<br /><strong>재료를 넣어주세요.</strong></h2><p>API 키, 모델 설정, 파일 또는 회의록 전문을 입력합니다.</p></div><div className="stage-card input-card"><div className="card-top"><span>AI 엔진과 인증</span><span className="status-pill">필수 설정</span></div><div className="provider-switch" role="group" aria-label="요약 엔진 선택"><button className={provider === "openai" ? "active" : ""} onClick={() => setProvider("openai")}>◒ &nbsp; OpenAI</button><button className={provider === "gemini" ? "active" : ""} onClick={() => setProvider("gemini")}>✦ &nbsp; Gemini</button></div><label className="field-label" htmlFor="api-key">{provider === "openai" ? "OpenAI" : "Gemini"} API 키 <span>필수</span></label><input id="api-key" className="text-input" type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="API 키를 입력하세요" autoComplete="off" /><div className="model-row"><span>기본 모델</span><strong>{model.label}</strong><code>{model.id}</code></div><div className="card-top source-heading"><span>회의록 전문</span><span className="optional-pill">파일 또는 텍스트</span></div><div className={`dropzone ${file ? "has-file" : ""}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void acceptFile(event.dataTransfer.files[0]); }} onClick={() => inputRef.current?.click()} role="button" tabIndex={0}><input ref={inputRef} type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => void acceptFile(event.target.files?.[0])} hidden /><div className="upload-icon">↑</div><strong>{file ? file.name : "DOCX 파일을 드래그하거나 클릭하세요"}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB · 본문 추출 완료` : "최대 10MB까지 업로드"}</span></div><textarea className="transcript-input" value={transcript} onChange={(event) => { setTranscript(event.target.value.slice(0, MAX_TEXT_LENGTH)); setFile(null); }} placeholder="또는 회의록 전문을 여기에 붙여 넣으세요" /><button className="primary-button" disabled={status === "reading"} onClick={() => { if (canContinue()) setStep(2); }}>{status === "reading" ? "파일 읽는 중…" : "다음: Process 설정 →"}</button>{error && <div className="error-box" role="alert">{error}</div>}<p className="security-copy">API 키는 이번 요청에만 사용되고 생성 후 즉시 비워집니다.</p></div></div>}
    {step === 2 && <div className="stage-page"><div className="stage-title"><span className="stage-kicker">02 / PROCESS</span><h2>어떤 회의록으로<br /><strong>정리할까요?</strong></h2><p>요약 스타일과 출력 분량을 정하면 AI가 그 기준에 맞춰 작성합니다.</p></div><div className="stage-card process-card"><div className="card-top"><span>요약 스타일</span><span className="optional-pill">하나 선택</span></div><div className="option-list">{STYLES.map((option) => <button key={option.value} className={style === option.value ? "selected" : ""} onClick={() => setStyle(option.value)}><span className="option-radio">{style === option.value ? "●" : "○"}</span><span><strong>{option.label}</strong><small>{option.note}</small></span></button>)}</div><div className="card-top source-heading"><span>출력 분량</span><span className="optional-pill">하나 선택</span></div><div className="length-grid">{LENGTHS.map((option) => <button key={option.value} className={length === option.value ? "selected" : ""} onClick={() => setLength(option.value)}><strong>{option.label}</strong><small>{option.note}</small></button>)}</div><div className="source-summary"><span>INPUT에 입력한 원문</span><strong>{file?.name || "직접 입력한 회의록"}</strong><small>{transcript.length.toLocaleString()}자 · {model.label}</small></div><div className="nav-buttons"><button className="secondary-button" onClick={() => setStep(1)}>← 이전</button><button className="primary-button" onClick={generateMinutes}>회의록 생성하기 →</button></div></div></div>}
    {step === 3 && <div className="stage-page output-page"><div className="stage-title"><span className="stage-kicker">03 / OUTPUT</span><h2>완성된 회의록을<br /><strong>가져가세요.</strong></h2><p>검토 후 복사하거나 Markdown 파일로 다운로드할 수 있습니다.</p></div><div className="stage-card output-card"><div className="card-top"><span>최종 보고서</span>{result && <div className="result-actions"><button onClick={() => navigator.clipboard.writeText(result)}>복사</button><button onClick={downloadResult}>↓ .md</button></div>}</div>{status === "generating" && <div className="loading-result"><div className="loading-orbit">✦</div><strong>회의록을 작성하고 있습니다…</strong><span>선택한 스타일과 분량을 적용하는 중입니다.</span></div>}{status === "error" && <div className="loading-result"><div className="loading-orbit error-orbit">!</div><strong>생성하지 못했습니다.</strong><span>{error}</span><button className="secondary-button" onClick={() => setStep(1)}>입력으로 돌아가기</button></div>}{status === "success" && <div className="markdown-result" dangerouslySetInnerHTML={{ __html: renderMarkdown(result) }} />}{status === "success" && <div className="output-footer"><button className="secondary-button" onClick={() => { setStep(1); setResult(""); setStatus("idle"); setError(""); }}>새 회의록 만들기</button><span>{STYLES.find((item) => item.value === style)?.label} · {LENGTHS.find((item) => item.value === length)?.label}</span></div>}</div></div>}
  </section><footer><span>회의록 자동 생성기 · AI-powered meeting minutes</span><span>Input · Process · Output</span></footer></main>;
}
